af-south-1:
  amazonlinux2023: ami-0baf59b626295c4bd
  rhel8: ami-0f3626218aa340648
  rhel9: ami-0cb1d6ad21772c835
  rocky8: ami-0f6740cc2de201555
  rocky9: ami-0d1c77289fe17484a
ap-east-1:
  amazonlinux2023: ami-0d36de2c5969b3539
  rhel8: ami-0567dec70e4b0af65
  rhel9: ami-0a00b12a51c231f99
  rocky8: ami-0c839768188cedbda
  rocky9: ami-09b42a680f493b03c
ap-northeast-1:
  amazonlinux2023: ami-08a59875ad2a26a5f
  rhel8: ami-042eeb1edb0b6c871
  rhel9: ami-0a77f7b7e2a7e9e19
  rocky8: ami-0025f1507e375f161
  rocky9: ami-0bdd4b6c4c6feca84
ap-northeast-2:
  amazonlinux2023: ami-077ad873396d76f6a
  rhel8: ami-098fcbf3441963062
  rhel9: ami-0b20135730887dc5f
  rocky8: ami-05d54bac15231e6fa
  rocky9: ami-06b18c6a9a323f75f
ap-northeast-3:
  amazonlinux2023: ami-03ebc643cdc3ac711
  rhel8: ami-08a18632363377c24
  rhel9: ami-087be824994962471
  rocky8: ami-039262f94e381ba82
  rocky9: ami-02da14a96759f4bdf
ap-south-1:
  amazonlinux2023: ami-01b6d88af12965bb6
  rhel8: ami-03b7070b7406f4e29
  rhel9: ami-02041feaeda79b4ad
  rocky8: ami-053ac9a936bd4459e
  rocky9: ami-08e313580b7dba0a6
ap-south-2:
  amazonlinux2023: ami-0cbe896ecf507b2a4
  rhel8: ami-0205e6d4b79c65b28
  rhel9: ami-02965f34c664643ee
  rocky8: ami-03e7e740ffbaecda1
  rocky9: ami-0aceb9334e1c25d36
ap-southeast-1:
  amazonlinux2023: ami-05fd46f12b86c4a6c
  rhel8: ami-05fb46ceb68b1bfdd
  rhel9: ami-05377537700a398ae
  rocky8: ami-0506f2d559a79a962
  rocky9: ami-0058131e22d7c740c
ap-southeast-2:
  amazonlinux2023: ami-0059ed5a3aacdfe15
  rhel8: ami-009b00c0c21930c01
  rhel9: ami-09b057cd644d1e4e5
  rocky8: ami-0c470b32d41481ad6
  rocky9: ami-0e3d660a2b0748434
ap-southeast-3:
  amazonlinux2023: ami-0abd1204e911fa550
  rhel8: ami-062938c5e0fbf56b9
  rhel9: ami-00de88e881f30d6cc
  rocky8: ami-04835cbf92d9614b9
  rocky9: ami-08187f3dae26981ad
ap-southeast-4:
  amazonlinux2023: ami-079aeeb40d0987157
  rhel8: ami-057e39eef1ce363d7
  rhel9: ami-0573e755612d12103
  rocky9: ami-07fb36516f7d1f529
ca-central-1:
  amazonlinux2023: ami-00959a3c022b1cc1e
  rhel8: ami-0b7ffb6b3a23d0e90
  rhel9: ami-07a0ee7a51a386be3
  rocky8: ami-0829e4c2a7a2dcce1
  rocky9: ami-0dc728f2209249218
eu-central-1:
  amazonlinux2023: ami-0444794b421ec32e4
  rhel8: ami-08eaea68c8899746d
  rhel9: ami-01d718c210035e8f4
  rocky8: ami-03ca52fa7cdd00b6a
  rocky9: ami-0974816532424c446
eu-central-2:
  amazonlinux2023: ami-06081dcb2709635e2
  rhel8: ami-01702d50f36a09821
  rhel9: ami-09110e91e73ed2fd2
  rocky8: ami-0a5aa73e9c888d9d7
  rocky9: ami-0bade0ccdcb3b5d42
eu-north-1:
  amazonlinux2023: ami-043339ea831b48099
  rhel8: ami-0dc09daa167ea0dba
  rhel9: ami-0325b265f53c6be7c
  rocky8: ami-07337a8cbe0c562e0
  rocky9: ami-08a91dd538f707083
eu-south-1:
  amazonlinux2023: ami-02368f5c72a096468
  rhel8: ami-0ccb11089007235a1
  rhel9: ami-05835c7f37ea2f768
  rocky8: ami-0112b02935b39c072
  rocky9: ami-09157a1cc0d8d7bd8
eu-south-2:
  amazonlinux2023: ami-03c239b7bf83c227e
  rhel8: ami-0b621332e2addd26b
  rhel9: ami-0b811bffa1f8a557b
  rocky8: ami-01e854fdb97099506
  rocky9: ami-09ff808003eb6a15f
eu-west-1:
  amazonlinux2023: ami-091a906f2e1e40076
  rhel8: ami-065b91f67dd493743
  rhel9: ami-0cb95ced7337e06e1
  rocky8: ami-0c14153c77f34b870
  rocky9: ami-09f73ba1beba9ad07
eu-west-2:
  amazonlinux2023: ami-0971f6afca696ace6
  rhel8: ami-09d0ac36ee4c107da
  rhel9: ami-017249f44aae39eff
  rocky8: ami-020c6cfb9f8b61b53
  rocky9: ami-05a5686f0de7aa5d5
eu-west-3:
  amazonlinux2023: ami-03601e822a943105f
  rhel8: ami-0bd9c415abb038cd4
  rhel9: ami-0b9b2007e369f4293
  rocky8: ami-07b9b3580fd50d52d
  rocky9: ami-05e6a5fbf52bcf86a
il-central-1:
  amazonlinux2023: ami-082ed0dba799bc39c
  rhel8: ami-0e1318d459f1d01f1
  rhel9: ami-0dd653ece6b8e8219
me-central-1:
  amazonlinux2023: ami-06af995c6c751efff
  rhel8: ami-054f264e93f32f943
  rhel9: ami-0225af1e7b2e460e5
  rocky8: ami-04261ed32e4298d90
  rocky9: ami-03102da6cb6cc7c39
me-south-1:
  amazonlinux2023: ami-050df2add2abc2fea
  rhel8: ami-0070b09f2849280fa
  rhel9: ami-04ffaa9bf5c182ff2
  rocky8: ami-07072a8bd6c72a066
  rocky9: ami-0f1af60b10870546d
sa-east-1:
  amazonlinux2023: ami-082daca2e7d60abda
  rhel8: ami-027454ed25e6ec32d
  rhel9: ami-027910aa765d77130
  rocky8: ami-0070a028fc72c8f48
  rocky9: ami-01d0e68ff218b8ad8
us-east-1:
  amazonlinux2023: ami-08982f1c5bf93d976
  rhel8: ami-0b199850d21f36238
  rhel9: ami-0ea1a49a8f4f31832
  rocky8: ami-011ef2017d41cb239
  rocky9: ami-0f2425d4cce4e97dd
us-east-2:
  amazonlinux2023: ami-0ca4d5db4872d0c28
  rhel8: ami-0b0e825b34a8c218e
  rhel9: ami-0f4412a999926c130
  rocky8: ami-02391db2758465a87
  rocky9: ami-0e529d862bbe9899c
us-gov-west-1:
  amazonlinux2023: ami-065697da90e42d60e
  rhel8: ami-008177b99929ea0db
  rhel9: ami-045a012096d84fb13
us-west-1:
  amazonlinux2023: ami-00142eb1747a493d9
  rhel8: ami-0b7f0f85ce309831f
  rhel9: ami-0e30fb4f5acf66d4c
  rocky8: ami-054c64de4b29296be
  rocky9: ami-0112e62b61894b311
us-west-2:
  amazonlinux2023: ami-06a974f9b8a97ecf2
  rhel8: ami-069fe92d07d6b4cf7
  rhel9: ami-086730b1f427d6f3d
  rocky8: ami-0f74cc83310468775
  rocky9: ami-0adebe3adcec1fa34
